### ISSUE TITLE
Automatic determination of decaying/annihilating nature of DM at dep resolution time  

### ISSUE THREAD

**Issue by patscott** [GambitBSM/gambit#241]
With the new routines coming in in GUM 1.0 via #228, it becomes possible to have decaying DM work natively in DarkBit.  However, the detection of such models is not fully automatic, in that you now need to give a rule such as 
```yaml
  # The model is annihilating DM, not decaying
  - capability: GA_Yield
    function: GA_AnnYield_General
```
in every single YAML file in order to tell the dep resolver whether to compute gamma-ray yields assuming that DM can decay or annihilate.  This is something that should be worked out from the model in use though, and should not require the user to choose by hand like this.  

The current setup also fails to permit situations where the DM can both decay *and* annihilate.
