### ISSUE TITLE
Backends option in rules section is not taken into account

### ISSUE THREAD

**Issue by tegonzalo** [GambitBSM/gambit#323]
I just discovered that rules like this
```
- capability: my_capability
  function: my_function
  backends:
    - {backend: my_backend, version: 0.0}
```
do nothing. Even though a lot of our error messages tell the user to do this, it doesn't actually work. It only works if one specifies the capability of the backend requirement, i.e. `{capability: my_be_req, backend: my_backend, version: 0.0}`, but not the above.

I have some preliminary fix to solve this, but still needs testing, so I created this issue to remind myself.
