### ISSUE TITLE
New YAML keyword for linking parameters to user-defined priors

### ISSUE THREAD

**Issue by anderkve** [GambitBSM/gambit#418]
(This Issue follows from a discussion in a Core WG meeting. We decided to do this instead of implementing the hack/fix in the now closed PR https://github.com/GambitBSM/gambit/pull/415.)

We should introduce a new keyword `in_priors` (or similar) to be used in the `Parameters` section of YAML files, to specify that the prior for a given parameter is specified in the `Priors` section of the YAML file. An example with two different 2D Gaussian priors would look something like this:

``` yaml
Parameters:
  SomeModel:
    par1: in_priors
    par2: in_priors
    par3: in_priors
    par4: in_priors

Priors:
  my_prior_1:
    parameters: ["SomeModel::par1", "SomeModel::par2"]
    prior_type: gaussian
    mu: [18.0, 5.0]
    sigma: [3.0, 1.0]

  my_prior_2:
    parameters: ["SomeModel::par3", "SomeModel::par4"]
    prior_type: gaussian
    mu: [0.0, 0.0]
    sigma: [1.0, 1.0]
```

Our current system for doing this is broken, since ScannerBit expects empty parameter entries like 

``` yaml
Parameters:
  SomeModel:
    par1:
    par2:
    par3:
    par4:
```
but uses the `Options` class to collect this info, and the `Options` class doesn't allow empty entries. (And it shouldn't.)
